### ISSUE TITLE
项目还是测试阶段?

### ISSUE THREAD

**Issue by SexyBeast233** [Martin2877/btab#6]
项目还在测试阶段吗 生成的sqlite全空 任意密码都是认证成功 然后新请求token超时 400返回错误?

**Comment by Martin2877** [comment]
1. 目前已经较为稳定的发布版本，可以试试最新版本；
2. 生成的sqlite是空的，初次使用时会初始化数据库表，但是是可用的；
3. 默认任何密码都可认证成功，登录页面还没做多用户；
4. token 超时的问题我这边没有出现，可以尝试新版本；

**Comment by SexyBeast233** [comment]
新版本功能已正常
